---
# roles/starship/defaults/main.yml

## Binary Management

starship_binary_state: "present"

starship_binary_version: "v1.15.0"
starship_binary_url: "https://github.com/starship/starship/releases/download/{{ starship_binary_version }}/starship-x86_64-unknown-linux-gnu.tar.gz"
starship_binary_checksum: "https://github.com/starship/starship/releases/download/{{ starship:binary_version }}/starship-x86_64-unknown-linux-gnu.tar.gz.sha256"

starship_binary_location: "/usr/local/bin"
...
