---
# roles/hadolint/defaults/main.yml

hadolint_binary_state: "present"

hadolint_binary_version: "v2.12.0"
hadolint_binary_url: "https://github.com/hadolint/hadolint/releases/download/{{ hadolint_binary_version }}/hadolint-Linux-x86_64"

hadolint_binary_location: "/usr/local/bin"
...
