---
# roles/cirrus_cli/tasks/main.yml

## Binary Management

- name: "Manage cirrus-cli Binary Path"
  ansible.builtin.file:
    name: "{{ cirrus_cli_binary_location }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: 0755
  become: true
  tags:
    - "cirrus"
    - "cirrus_cli"
    - "binary"

- name: "Download cirrus-cli Binary"
  ansible.builtin.get_url:
    url: "{{ cirrus_cli_binary_url }}"
    dest: "{{ cirrus_cli_binary_location }}/cirrus"
    owner: "root"
    group: "root"
    mode: 0755
  become: true
  tags:
    - "cirrus"
    - "cirrus_cli"
    - "binary"
...
