---
# roles/gnome_config/tasks/appearance.yml

- name: "Set Background"
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file://{{ gnome_config_background_path }}'"
    state: "present"
  tags:
    - "gnome"
    - "appearance"
    - "configuration"
...
