---
# roles/gnome_config/tasks/display.yml

- name: "Manage Nightlight Enabled"
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "{{ gnome_config_night_light_enabled }}"
    state: "present"
  tags:
    - "gnome"
    - "display"
    - "configuration"

- name: "Manage Nightlight Auto Schedule"
  community.general.dconf:
    # yamllint disable-line rule:line-length
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic"
    value: "{{ gnome_config_night_light_schedule }}"
    state: "present"
  tags:
    - "gnome"
    - "display"
    - "configuration"
...
