---
# roles/gnome_config/tasks/mouse.yml

- name: "Touchpad - Tap to Click"
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "{{ gnome_config_touchpad_tap_to_click }}"
    state: "present"
  tags:
    - "gnome"
    - "configuration"
    - "mouse"
...
